### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by re-becca** [qld-gov-au/swe#13]
Use this issue to discuss the [cards component](https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/cards).

**Comment by LisaBee** [comment]
Is the border above the call to action button really necessary? I feel it's cleaner without, and doesn't require as much vertical space (since you don't need two lots of padding).



![Image](https://user-images.githubusercontent.com/9208750/228986495-79daa475-4a87-4f6e-8a3e-808d7f8322e5.png)

**Comment by re-becca** [comment]
Thanks @LisaBee, we think this is a great suggestion and have planned to include it in the next release (4.3.0).

**Comment by amitdeydotme** [comment]
Hi LisaBee,

Nice to meet you :)

The current card component is I think little outdated and hard to manage. To brief that, I have added couple of screenshots from the current SWE kit below to put light on the subject:
 
<img width="227" alt="Screen Shot 2023-05-10 at 2 00 18 pm" src="https://github.com/qld-gov-au/swe/assets/133072204/8af42d93-68c4-45f2-bf9e-381d3ed7071e">

<img width="974" alt="Screen Shot 2023-05-10 at 1 50 09 pm" src="https://github.com/qld-gov-au/swe/assets/133072204/3b254c28-bf5f-4550-b18c-1cf4e0f354b2">

<h4>The above component is fragmented and static at the moment which doesn't help in creating a fluid template for a web page. </h4>

So, in order to address the above problem, I have come up with one single card component that consists of 4 atoms to make a card component for all possible use cases:

**Image**, **Title**, **Description** and a **Button**

<img width="403" alt="Screen Shot 2023-05-10 at 1 52 46 pm" src="https://github.com/qld-gov-au/swe/assets/133072204/caf5cf98-2820-4d20-b2f1-8b42a185e6a8">

<h4>Some instances of the master card component to address various uses cases are below. Given any use cases the card layout is fluid and dynamic with content.</h4>


<img width="853" alt="Screen Shot 2023-05-10 at 2 46 15 pm" src="https://github.com/qld-gov-au/swe/assets/133072204/ab58dd9c-516f-438d-9394-e79dd2d7fab4">

Please let me know if you have any questions. Thank you!

**Comment by re-becca** [comment]
@LisaBee your suggestion to _remove the border above the call to action button_ has been released today in SWE v4.3.0. Thanks again for sharing it here.

**Comment by amitdeydotme** [comment]
[like]  Amit Dey reacted to your message:
________________________________
