### ISSUE TITLE
Topic index page

### ISSUE THREAD

**Issue by re-becca** [qld-gov-au/swe#3]
Use this issue to discuss the [topic index page template](https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/templates/topic-index-page).

**Comment by latchmananr** [comment]
Hello team,

I was wondering if we could switch the SWE topic index page to a single column layout instead of the current two columns. 

The current layout is causing some of the link texts to wrap into multiple lines with 2-3 words each line, which makes it difficult to read or scan. 

A single column layout would make the page look cleaner and the links easier to read and scan.
 
Thanks 😊

**Current:**
![Image](https://user-images.githubusercontent.com/8637600/226239845-4aee0e24-0658-44c4-b146-7ba65ac66e5f.png)


**Proposed:**
![Image](https://user-images.githubusercontent.com/8637600/226239829-f27a8124-fe2e-44f9-b7f2-1cd01b3793e8.png)

**Comment by re-becca** [comment]
Thanks Ray. Great suggestion for improving readability of content.
 
A review of the topic index page template is up next on the [SWE roadmap.](https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/swe-roadmap) If by any chance you have user-based evidence to support this, could you please share it with us? E.g. Mouseflow/GA/survey/observational insights.

**Comment by latchmananr** [comment]
Thanks, Bec.
 
At this stage, it is more from my own experience navigation the site especially on a **laptop with a smaller resolution**. 

Also, there is research on the F-Shaped pattern, which may relate to this.
 
For an example:
![image](https://user-images.githubusercontent.com/8637600/226497002-09621be9-0b93-46bf-9dac-85a214a06849.png)

Changing it to a single column, it immediately improves the readability
![image](https://user-images.githubusercontent.com/8637600/226497284-76820b32-c2fe-4ab1-925a-334a6809b083.png)

**Comment by LisaBee** [comment]
+1 from DES.
I think a while back Corrin was working on something like this but it didn't get anywhere.

**Comment by cathy-may** [comment]
Hi, team

Could we please get an option to have a context sentence (short description) on a tile, rather than automatically pulling in child pages as deep links?

I'm creating a new section of content for native title, and we'd like users to go to the parent page first to help explore their options and choose the right journey with context. If there are deep links, they'll lose that context and this might result in a more confusing journey. Yes, it's one more click to a landing page rather than going direct to a content page, but the information on that landing page kicks off a whole journey, and sets a tone for the content overall. 

I know there'll be a workaround in Squiz to 'hide' the child pages, but it'd be nice to have this as a flexible option. There have been other times where a short description could really help a user understand what the following information is about. For example, the Native Title Works Procedures is a bit inexplicable without context:
![image](https://github.com/qld-gov-au/swe/assets/137975364/752d9e76-5a87-4ae0-9121-a71671cad908)

**Comment by latchmananr** [comment]
> Hi, team
> 
> Could we please get an option to have a context sentence (short description) on a tile, rather than automatically pulling in child pages as deep links?
> 
> I'm creating a new section of content for native title, and we'd like users to go to the parent page first to help explore their options and choose the right journey with context. If there are deep links, they'll lose that context and this might result in a more confusing journey. Yes, it's one more click to a landing page rather than going direct to a content page, but the information on that landing page kicks off a whole journey, and sets a tone for the content overall.
> 
> I know there'll be a workaround in Squiz to 'hide' the child pages, but it'd be nice to have this as a flexible option. There have been other times where a short description could really help a user understand what the following information is about. For example, the Native Title Works Procedures is a bit inexplicable without context: ![image](https://user-images.githubusercontent.com/137975364/249344172-752d9e76-5a87-4ae0-9121-a71671cad908.png)

This is another example where we have more than 20 pages (modules) under the parent, It will be more useful to have a descriptive text for the parent page than a list of link to first 4 modules 

![image](https://github.com/qld-gov-au/swe/assets/8637600/5101160f-5d03-43ce-9988-aae240f6d95e)

**Comment by latchmananr** [comment]
> Hi, team
> 
> Could we please get an option to have a context sentence (short description) on a tile, rather than automatically pulling in child pages as deep links?
> 
> I'm creating a new section of content for native title, and we'd like users to go to the parent page first to help explore their options and choose the right journey with context. If there are deep links, they'll lose that context and this might result in a more confusing journey. Yes, it's one more click to a landing page rather than going direct to a content page, but the information on that landing page kicks off a whole journey, and sets a tone for the content overall.
> 
> I know there'll be a workaround in Squiz to 'hide' the child pages, but it'd be nice to have this as a flexible option. There have been other times where a short description could really help a user understand what the following information is about. For example, the Native Title Works Procedures is a bit inexplicable without context: ![image](https://user-images.githubusercontent.com/137975364/249344172-752d9e76-5a87-4ae0-9121-a71671cad908.png)

This is another example where we have more than 20 pages (modules) under the parent, It will be more useful to have a descriptive text for the pages than link to first 4 modules 

![image](https://github.com/qld-gov-au/swe/assets/8637600/5101160f-5d03-43ce-9988-aae240f6d95e)

**Comment by latchmananr** [comment]
> Hi, team
> 
> Could we please get an option to have a context sentence (short description) on a tile, rather than automatically pulling in child pages as deep links?
> 
> I'm creating a new section of content for native title, and we'd like users to go to the parent page first to help explore their options and choose the right journey with context. If there are deep links, they'll lose that context and this might result in a more confusing journey. Yes, it's one more click to a landing page rather than going direct to a content page, but the information on that landing page kicks off a whole journey, and sets a tone for the content overall.
> 
> I know there'll be a workaround in Squiz to 'hide' the child pages, but it'd be nice to have this as a flexible option. There have been other times where a short description could really help a user understand what the following information is about. For example, the Native Title Works Procedures is a bit inexplicable without context: ![image](https://user-images.githubusercontent.com/137975364/249344172-752d9e76-5a87-4ae0-9121-a71671cad908.png)

This is another example where we have more than 20 pages (modules) under the parent, It will be more useful to have a descriptive text for the pages than link to first 4 modules 

![image](https://github.com/qld-gov-au/swe/assets/8637600/5101160f-5d03-43ce-9988-aae240f6d95e)

**Comment by re-becca** [comment]
Hi @cathy-may and @latchmananr, thanks for the above suggestion. To keep you updated: we're working on a bunch of topic index template improvements, including this option suggested by Cathy - it'll likely be applied on a page basis for consistency. Will keep you in the loop for feedback and testing.

**Comment by LisaBee** [comment]
Hi, regarding the topic page asset listing on QGov's Matrix (#260) - where it's listing Redirect/Link assets, could the links used be to the asset/URL the link is going to, instead of an internal URL?  It's quite misleading as it is, since when you hover over a link to see where it's going to go it's not accurate.

Where this snippet has %asset_url%:
<li><a href="%asset_url%">%asset_attribute_short_name%</a></li>

on our sites we use something like:
%begin_asset_type^eq:Link%%link_url%%else_asset%%asset_type^eq:Redirect Page:{redirect_url}:{asset_url}%%end_asset%

It accommodates Link and Redirect assets, with a fail back to a regular asset URL.

**Comment by ghazal-salehi** [comment]
Hi @LisaBee,

Thanks for your comment. I understand. We can accomodate that.
Can you please share us a page with redirect assets and let us know of a link that is misleading because of redirection, so we can test on it in UAT?

Best Regards
Ghazal

**Comment by LisaBee** [comment]
Hi Ghazal. Thanks for looking into this.  
They are all misleading since it doesn't reflect the location of the page/site being linked to.  Especially when the link is to an agency or other external site, but it looks like the link goes to a page within QGov.
Example pages:
Land and vegetation management #61087  https://www.qld.gov.au/environment/land/management
Finding and applying for jobs #12411  https://www.qld.gov.au/jobs/finding

**Comment by ghazal-salehi** [comment]
Thanks for that. I have update the asset lister. Please see Pest management under https://oss-uat.clients.squiz.net/environment/land/management/_nocache
I was wondering if the issue was only for the <h2>s and not the child pages?

**Comment by LisaBee** [comment]
It could be for either, e.g. the parent to 'Land management' page where 'Pest management' is a child page https://oss-uat.clients.squiz.net/environment/land 
I would suggest updating consistently in both asset listings.

The change you've made so far looks good, thanks.  👍

**Comment by ghazal-salehi** [comment]
No worries @LisaBee. It is now done for sub pages as well. Please see https://oss-uat.clients.squiz.net/environment/land

I'll come back to you with some time estimation for the release. If it is not urgent the latest would be second week of January as part of SWE 4.4.0 release when we are implementing the proposed changes to the Topic Index Pages. The reason that we have to push it further is one month change freeze over the New Year. 

If that does not work for you we can plan something earlier.

Warm Regards
Ghazal

**Comment by LisaBee** [comment]
Thanks @ghazal-salehi.  It's not urgent, just something that's stood out to me for a while.

**Comment by re-becca** [comment]
Many of the above suggestions were incorporated into [release 4.4.0](https://github.com/qld-gov-au/qg-web-template/releases/tag/v4.4.0) - thanks everyone for your contributions.
